### ISSUE TITLE
Consider 

### ISSUE THREAD

**Issue by whmii** [thoughtbot/presskit#10]
@corwinharrell I havwe been working on a couple projects that use [middleman-gh-pages](https://github.com/neo/middleman-gh-pages) instead of [middleman-deploy](https://github.com/karlfreeman/middleman-deploy) and I've been having a better time with it. Also, there is asset cacheing that should resolve some of the stylesheet issues that we've been having.

**Comment by corwinharrell** [comment]
@whmii that's interesting, I actually had the opposite problem where middleman-gh-pages was giving me trouble. Looks like middleman-deploy has been updated much more recently as well. Anyways, whatever works. I'm still not sure what caused the trouble you were having initially besides the fact that it wasn't pointing to the right branch in the config file?

**Comment by tysongach** [comment]
@whmii Can this be closed?
